### PR TITLE
more random

### PR DESCRIPTION
**Pull request by peterferrie**

### CODE REVIEW

**Comment by donno2048** [comment]
Am I missing something or is it not that random? 😅

**Comment by peterferrie** [comment]
> Am I missing something or is it not that random? 😅

It's a counter whose value changes fairly quickly.
It's far more variable than the stack pointer.

**Comment by donno2048** [comment]
Yes but only one byte will be loaded into `ax` so it must be <0xff, which can be solved with `mov dx, 0x40` or something then `in ax, dx` but it adds bytes...

**Comment by peterferrie** [comment]
> Yes but only one byte will be loaded into `ax`

No, in ax,0x40 will read a 16-bit value from ports 0x40-41.

**Comment by donno2048** [comment]
Oh, it just seems like it on DOSBox because port 0x41 always outputs 0, is it a bug in DOSBox or something?

**Comment by donno2048** [comment]
BTW, my mistake came from this [instruction set reference](https://c9x.me/x86/html/file_module_x86_id_139.html), but I checked in the Intel manual and it's wrong...

**Comment by donno2048** [comment]
As far as I can see on DOSBox this
```asm
start:
in ax, 0x40
test ah, ah
jz start
ret
```
will never halt however 
```asm
start:
in al, 0x41
test al, al
jz start
ret
```
and
```asm
mov dx, 0x40
start:
in ax, dx
test ah, ah
jz start
ret
```

**Comment by peterferrie** [comment]
> As far as I can see on DOSBox this
> ```asm
> start:
> in ax, 0x40
> test ah, ah
> jz start
> ret
> ```
> will never halt however
> ```asm
> start:
> in al, 0x41
> test al, al
> jz start
> ret
> ```
> and
> ```asm
> mov dx, 0x40
> start:
> in ax, dx
> test ah, ah
> jz start
> ret
> ```

Then I have to wonder about your DOSBox version or configuration.
"in ax, imm8" and "in ax,dx" should behave equivalently.  The dx
version exists primarily to access ports > 255.
What DOSBox version are you using?  Which core in the config?

**Comment by donno2048** [comment]
I've tried every CPU but it produces the same result, I'm using DOSBox `0.74-3`

**Comment by donno2048** [comment]
> I've tried every CPU but it produces the same result, I'm using DOSBox `0.74-3`. Using a dynamic core seems to work (simple or normal won't) but it makes the game too fast to play...

@peterferrie

**Comment by donno2048** [comment]
It works on dosbox-x...

**Comment by peterferrie** [comment]
> I've tried every CPU but it produces the same result, I'm using DOSBox
> `0.74-3`

I can't explain the difference.  It works on real hardware.

**Comment by donno2048** [comment]
Just to make sure, the same thing won't work on port 0x5f for example (i.e. `in ax, 0x5f`) because of hardware limitations, right?

**Comment by peterferrie** [comment]
> Just to make sure, the same thing won't work on port 0x5f for example (i.e.
> `in ax, 0x5f`) because of hardware limitations, right?

It works there, and you'll get your key in ah instead of al.

**Comment by donno2048** [comment]
Yeah, I thought about using `in ax, 0x5F`, `aad` instead of `in al, 0x60`, `imul ax, BYTE 0xA`, wondered if that's even possible. I don't know what will port 0x5F output to `al` (I hope it's just 0) so don't know whether it's a good idea at all...

**Comment by peterferrie** [comment]
> Yeah, I thought about using `in ax, 0x5F`, `aad` instead of `in al, 0x60`,
> `imul ax, BYTE 0xA`, wondered if that's even possible. I don't know what
> will port 0x5F output to `al` (I hope it's just 0) so don't know whether
> it's a good idea at all...

port 0x5f is unassigned, so you might get lucky.

**Comment by donno2048** [comment]
Just tried,
```asm
in al, 0x60
shl ax, 0x8
aad
```
works, but
```asm
in ax, 0x5F
aad
```
won't, and even
```asm
in ax, 0x5F 
xor al, al
aad
```
won't, so I guess another DOSBox bug or it's not possible

**Comment by peterferrie** [comment]
That will be DOSBox biting you again, in that case. Try DOSBox-X or MAME,
etc. to see it working.

**Comment by peterferrie** [comment]
I'm sorry, I was wrong.  Since 0x5f isn't mapped, the behaviour depends entirely on hardware.  I have two machines that behave differently.  You can't rely on 0x60 being read.

**Comment by donno2048** [comment]
OK, thanks for the update!

**Pull request merged**
