### PR TITLE
restore starting position at center

### PR DESCRIPTION
**Pull request by hen-ter**
It gets tough now to wrestle more out of it but at least the snake starts in the center again...

### CODE REVIEW

**Comment by donno2048** [comment]
Wow, I saw it's possible to use `0xF9C` for `cx` for the masking and use the two `ja`s but thought it will be problematic with the `div cl` and `lds` and even though I thought it could be fixed with `lds dx,` it just meant the next dummy instruction will be problematic, but it turns out I should have just switched `cl` and `dl` awesome! Totally slipped by me.

**Comment by donno2048** [comment]
Intrested to know what's your background in assembly..?

**Comment by hen-ter** [comment]
> Wow, I saw it's possible to use `0xF9C` for `cx` for the masking and use the two `ja`s but thought it will be problematic with the `div cl` and `lds` and even though I thought it could be fixed with `lds dx,` it just meant the next dummy instruction will be problematic, but it turns out I should have just switched `cl` and `dl` awesome! Totally slipped by me.

Was struggling with that as well, 0xF9C just isn't suitable for dummy instructions. Also losing 0xA for the MUL in input handling had me worried initially.

**Comment by hen-ter** [comment]
> Intrested to know what's your background in assembly..?



> Intrested to know what's your background in assembly..?

Grew up with the C64 in the 80s with BASIC and assembly then moved on to PCs in the 90s with C and assembly.
Got hooked seeing Second Reality by Future Crew and got involved in the demo scene a bit.
Only did programming as a job shortly in the game industry in the late 90s and working on photogrammetry software in the early 2000s (mostly C/C++ but optimized assembly for performance relevant parts).

Now I'm "old", have too much free time on my hands and do things for fun randomly when my interest gets peeked but still there are very few things that give me more joy than trying to optimize stuff in assembly.

I've seen you're quite young - love it that this kind of coding lives on :)

**Comment by donno2048** [comment]
> > Wow, I saw it's possible to use `0xF9C` for `cx` for the masking and use the two `ja`s but thought it will be problematic with the `div cl` and `lds` and even though I thought it could be fixed with `lds dx,` it just meant the next dummy instruction will be problematic, but it turns out I should have just switched `cl` and `dl` awesome! Totally slipped by me.
> 
> Was struggling with that as well, 0xF9C just isn't suitable for dummy instructions. Also losing 0xA for the MUL in input handling had me worried initially.

Exactly!

**Comment by donno2048** [comment]
> > Intrested to know what's your background in assembly..?
> 
> Grew up with the C64 in the 80s with BASIC and assembly then moved on to PCs in the 90s with C and assembly. Got hooked seeing Second Reality by Future Crew and got involved in the demo scene a bit. Only did programming as a job shortly in the game industry in the late 90s and working on photogrammetry software in the early 2000s (mostly C/C++ but optimized assembly for performance relevant parts).
> 
> Now I'm "old", have too much free time on my hands and do things for fun randomly when my interest gets peeked but still there are very few things that give me more joy than trying to optimize stuff in assembly.
> 
> I've seen you're quite young - love it that this kind of coding lives on :)

Never heard of Second Reality will definitely look that up!

**Comment by donno2048** [comment]
I feel very lucky to have you involved, thanks!

**Comment by donno2048** [comment]
DAMN! Just saw Second Reality. What!

**Comment by hen-ter** [comment]
> DAMN! Just saw Second Reality. What!

Exactly! Imagine how my mind was blown 30 years ago...

**Comment by hen-ter** [comment]
> I feel very lucky to have you involved, thanks!

Thanks, my pleasure! I'm happy to have stumbled upon your project - in fact a good friend pointed me to it because he knew it would be right up my alley. And for sure it provided me with hours of fun so far.

**Pull request merged**
