### PR TITLE
new game mechanics

### PR DESCRIPTION
**Pull request by hen-ter**
Not sure if you'll like this one...

It saves 1 byte and imho makes the game more fun by introducing new mechanics.
Digested food turns into `O`, which doesn't grow the snake and turns into poison `Å` when consumed.
A tombstone `└` which kills you appears in the last position you died.
This is kind of a glitch that could be fixed with `push ds` before `mov si, sp`.

### CODE REVIEW

**Comment by donno2048** [comment]
I don't like the idea of changing the mechanics in such a dramatic fashion just for the sake of reducing one byte, thanks for the effort though!

**Comment by hen-ter** [comment]
> I don't like the idea of changing the mechanics in such a dramatic fashion just for the sake of reducing one byte, thanks for the effort though!

I look at it the the way, it makes the game more interesting and happens to also make it smaller ;)
Didn't really expect you to merge this but thought it was interesting nonetheless.

**Comment by donno2048** [comment]
It is an interesting take but I think it can't really be called snake

**Comment by donno2048** [comment]
@hen-ter is there a way I can contact you?

I tried writing an email but I don't know if you still use it

**Pull request closed without merging**
